### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by tkmxqrdxddd** [stepanse/openlyactive#1]
When will you start developing this project? I would very much like to have it, but there is 4 months without any commit.

**Comment by stepanse** [comment]
Hey, that's great to hear. I have had a few things come up in my personal life, however, I hope to get back to working on OpenlyActive soon.

Sorry that I don't have any concrete date, but I would like to release an MVP by the end of the year.

**Comment by tkmxqrdxddd** [comment]
add me as coworker, i will make it in a week, i ain't such a slow worker

**Comment by stepanse** [comment]
I'm sorry, I would really like this to at least in the beginning stay my personal project. But you're more than welcome to take this idea and make your own!

**Comment by tkmxqrdxddd** [comment]
OK @stepanse
